
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: piscine-backend
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: piscine-frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
