# Utilise une image Python légère
FROM python:3.10-slim

# Crée un répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier requirements.txt depuis le dossier parent
COPY ../requirements.txt .

# Installe les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copie tout le contenu du backend dans /app/backend
COPY . /app/backend

# Définit la commande de démarrage
CMD ["python", "/app/backend/main.py"]
